- name: Set up JDK
  uses: actions/setup-java@v4
  with:
    java-version: '21'
    distribution: 'temurin'

- name: Setup project
  run: |
    git submodule update --init --recursive
    chmod +x gradlew

- name: Build APK
  uses: android-actions/gradle-build@v2
  with:
    gradle-version: wrapper
    task: assembleRelease
